workflows:
  hotel-booking-qa:
    name: Hotel Booking QA Pipeline (MANUAL ONLY)
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      groups:
        - hotel_booking_secrets
      flutter: 3.24.0
      xcode: 15.2
      cocoapods: default
      
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
        
    # AUTOMATIC TRIGGERING DISABLED - MANUAL BUILDS ONLY
    # Remove the # below to re-enable auto builds later
    # triggering:
    #   events: []
    
    scripts:
      - name: Setup environment
        script: |
          echo "🔧 Setting up environment..."
          flutter doctor -v
          dart --version
          
      - name: Install dependencies
        script: |
          echo "📦 Installing dependencies..."
          flutter pub get
          
      - name: Install Patrol CLI
        script: |
          echo "🚁 Installing Patrol CLI..."
          dart pub global activate patrol_cli
          export PATH="$PATH:$HOME/.pub-cache/bin"
          patrol --version
          
      - name: Generate code
        script: |
          echo "🔨 Generating code..."
          dart run build_runner build --delete-conflicting-outputs
          
      - name: Run unit tests
        script: |
          echo "🧪 Running unit tests..."
          flutter test test/unit/ --coverage
          
      - name: Setup Android emulator for Patrol
        script: |
          echo "🤖 Setting up Android emulator for Patrol..."
          cd $ANDROID_HOME/tools
          echo "no" | avdmanager create avd --force -n patrol_test -k "system-images;android-34;google_apis;x86_64"
          emulator -avd patrol_test -no-audio -no-window &
          adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d "\r") ]]; do sleep 1; done'
          
      - name: Build Android APKs for Patrol
        script: |
          echo "📱 Building APKs for Patrol tests..."
          export PATH="$PATH:$HOME/.pub-cache/bin"
          patrol build android --target=integration_test/tests/dashboard_test.dart --verbose
          
      - name: Run Patrol Tests
        script: |
          echo "🔄 Running Patrol integration tests..."
          export PATH="$PATH:$HOME/.pub-cache/bin"
          
          patrol test integration_test/tests/dashboard_test.dart --verbose || true
          patrol test integration_test/tests/overview_test.dart --verbose || true
          
        test_report: android_native_test
        
    artifacts:
      - build/app/outputs/apk/debug/app-debug.apk
      - build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk
      - coverage/**
      - screenshots/**
      
    publishing:
      slack:
        channel: '#qa-automation'
        notify_on_build_start: false
        notify:
          success: false  # Disabled for manual builds
          failure: true