workflows:
  hotel-booking-patrol-qa:
    name: Hotel Booking Patrol QA
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - hotel_booking_secrets
      flutter: 3.24.0
      vars:
        SERPAPI_API_KEY: $SERPAPI_API_KEY
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/.pub-cache/bin
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'develop'
          include: true
    scripts:
      - name: Setup Environment
        script: |
          flutter doctor -v
          flutter --version
      - name: Install Dependencies
        script: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
      - name: Install Patrol CLI
        script: |
          dart pub global activate patrol_cli
          export PATH="$PATH:$HOME/.pub-cache/bin"
          patrol --version
      - name: Run Flutter Tests
        script: |
          flutter test test/unit/ test/widgets/ --reporter=compact
      - name: Build APKs with Patrol
        script: |
          export PATH="$PATH:$HOME/.pub-cache/bin"
          patrol build android \
            --target integration_test/ \
            --dart-define=SERPAPI_API_KEY="$SERPAPI_API_KEY" \
            --verbose
      - name: Verify APK Build
        script: |
          ls -la build/app/outputs/apk/debug/
          ls -la build/app/outputs/apk/androidTest/debug/
          if [ ! -f "build/app/outputs/apk/debug/app-debug.apk" ]; then
            echo "❌ Main APK not found"
            exit 1
          fi
          if [ ! -f "build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk" ]; then
            echo "❌ Test APK not found"
            exit 1
          fi
          echo "✅ APKs verified successfully"
      - name: Run Integration Tests on emulator.wtf
        script: |
          ew-cli \
            --app build/app/outputs/apk/debug/app-debug.apk \
            --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
            --device Pixel7Atd \
            --device-api 33 \
            --use-orchestrator \
            --clear-package-data \
            --with-coverage \
            --record-video \
            --timeout 25 \
            --outputs-dir test-results \
            --num-shards 2
        test_report: test-results/**/*.xml
    artifacts:
      - build/app/outputs/apk/debug/app-debug.apk
      - build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk
      - test-results/**
    publishing:
      email:
        recipients:
          - ahmad@junoon.dev
        notify:
          failure: true