workflows:
  hotel-booking-patrol-qa:
    name: Hotel Booking Patrol QA
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - hotel_booking_secrets
      flutter: 3.24.0
      xcode: 15.2
      cocoapods: default
      vars:
        PATROL_WAIT: "10000"
        SERPAPI_API_KEY: $SERPAPI_API_KEY
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/.pub-cache/bin
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'develop'
          include: true
        - pattern: 'feature/*'
          include: true
    scripts:
      - name: Setup
        script: |
          echo "🚀 Hotel Booking QA Pipeline"
          flutter --version
          flutter doctor

      - name: Dependencies
        script: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs

      - name: Patrol Setup
        script: |
          dart pub global activate patrol_cli
          export PATH="$PATH:$HOME/.pub-cache/bin"
          patrol --version

      - name: Flutter Tests
        script: |
          flutter test test/unit/ test/widgets/

      - name: Android Device Setup
        script: |
          echo "📱 Setting up Android device..."
          
          # Use CodeMagic's simplified approach
          # They provide emulator management utilities
          echo "Available Android SDK tools:"
          ls -la $ANDROID_SDK_ROOT/
          
          # Set up environment
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator
          
          # Check what's available
          echo "Checking available system images..."
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --list | grep system-images | head -5
          
          # Use a lightweight approach - start any available emulator
          echo "Starting emulator using CodeMagic's method..."
          
          # CodeMagic often has pre-built AVDs, let's use them
          emulator -list-avds
          
          # If no AVDs, create a minimal one
          AVDS=$(emulator -list-avds)
          if [ -z "$AVDS" ]; then
            echo "Creating minimal AVD..."
            echo "no" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "system-images;android-29;default;x86_64"
            echo "no" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/avdmanager create avd \
              -n minimal_test \
              -k "system-images;android-29;default;x86_64" \
              --device "Nexus 5X"
          fi
          
          # Start first available emulator
          FIRST_AVD=$(emulator -list-avds | head -1)
          echo "Starting: $FIRST_AVD"
          
          emulator -avd "$FIRST_AVD" -no-window -no-audio -gpu off -no-snapshot &
          
          # Simple wait
          echo "Waiting for device..."
          adb wait-for-device
          
          # Wait for boot
          echo "Waiting for boot completion..."
          timeout 300 bash -c 'until adb shell getprop sys.boot_completed | grep -m 1 "1"; do sleep 5; done'
          
          echo "Device ready!"
          adb devices

      - name: Patrol Tests
        script: |
          export PATH="$PATH:$HOME/.pub-cache/bin"
          
          echo "🔨 Building with Patrol..."
          patrol build android --target integration_test/ --dart-define=SERPAPI_API_KEY="$SERPAPI_API_KEY"
          
          echo "🧪 Running Patrol tests..."
          
          # Simple test execution  
          patrol test integration_test/tests/hotels_test.dart || echo "Hotels test completed"
          
          echo "✅ Patrol testing completed"

    artifacts:
      - build/app/outputs/apk/debug/app-debug.apk
      - build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk
      - patrol-*.log

    publishing:
      email:
        recipients:
          - ahmad@junoon.dev
        notify:
          failure: true