# Device Configuration for Hotel Booking App Tests
# Configured for your specific available devices

environments:
  local:
    ios_simulators:
      iphone_16_plus:
        name: "iPhone 16 Plus"
        udid: "AEEFBF8D-12AB-4AC1-9BA7-9751ED8AC5D8"
        version: "18.0"
        runtime: "iOS-18-0"
        device_type: "com.apple.CoreSimulator.SimDeviceType.iPhone-16-Plus"
        status: "booted"
        description: "Primary iOS test device"
    
    android_emulators:
      pixel_7:
        name: "Pixel 7"
        avd_name: "Pixel_7"
        api_level: 36
        target: "android-36"
        abi: "arm64-v8a"
        tag: "google_apis_playstore"
        description: "Android 14.0 (API 36) | arm64-v8a | Google Play"
        ram_size: "2048"
        heap_size: "228"

  firebase_test_lab:
    ios_devices:
      iphone_15_pro:
        model: "iphone15pro"
        model_name: "iPhone 15 Pro"
        version: "18.0"
        locale: "en"
        orientation: "portrait"
        device_capacity: "Medium"
        description: "Firebase Test Lab iOS device"
    
    android_devices:
      pixel_8:
        model: "shiba"
        model_name: "Pixel 8"
        version: "34"
        locale: "en"
        orientation: "portrait"
        device_capacity: "High"
        description: "Firebase Test Lab Android device"

execution:
  default_platform: "local"
  parallel_execution: true
  max_parallel_devices: 2
  device_startup_timeout: 120
  test_timeout: 600
  retry_count: 2
  
  preferred_devices:
    local_ios: "iphone_16_plus"
    local_android: "pixel_7"
    firebase_ios: "iphone_15_pro"
    firebase_android: "pixel_8"
