name: Hotel Booking QA Pipeline

on:
  push:
    branches: [main, master, develop]
    paths:
      - "lib/**"
      - "test/**"
      - "integration_test/**"
      - "android/**"
      - "pubspec.yaml"
  pull_request:
    branches: [main, master, develop]

jobs:
  unit_and_widget_tests:
    name: Unit & Widget Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Generate Code
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run All Tests
        run: flutter test

  firebase_integration_tests:
    name: Integration Tests (Firebase)
    runs-on: ubuntu-latest
    needs: unit_and_widget_tests
    timeout-minutes: 45

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"
          cache: true

      - name: Setup Patrol CLI
        run: |
          dart pub global activate patrol_cli
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: flutter pub get

      - name: Generate Code (if needed)
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Build Android APKs for Integration Tests
        run: patrol build android --target integration_test/ --release

      - name: Run Integration Tests on Firebase Test Lab
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          gcloud firebase test android run \
            --type instrumentation \
            --app build/app/outputs/apk/debug/app-debug.apk \
            --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
            --device model=shiba,version=34,locale=en,orientation=portrait \
            --timeout 20m \
            --results-bucket=${FIREBASE_PROJECT_ID}-test-results \
            --environment-variables clearPackageData=true \
            --use-orchestrator \
            --project $FIREBASE_PROJECT_ID